[package]
name = "zlib"
version = "1.3.1"
nanvix-version = "0.23.43"

[builds]
[builds.matrix]
platforms = ["microvm"]
modes = ["standalone"]
memory = ["256mb"]

[toolchain]
kind = "nanvix-sdk"
provider = "c-clang"
sdk-version = "v0.23.43-sdk.1"
sdk-image = "ghcr.io/nanvix/nanvix-sdk-c-clang"
sdk-digest = "sha256:faaf7a16fcd94df1f4fea80c146bb3fb732f78e78bc8f530c010256141899dc8"
