[package]
name = "zlib"
version = "1.3.1"
nanvix-version = "0.24.36"

[builds]
[builds.matrix]
platforms = ["microvm"]
modes = ["standalone"]
memory = ["256mb"]

[toolchain]
kind = "nanvix-sdk"
provider = "c-clang"
sdk-version = "v0.24.36-sdk.1"
sdk-image = "ghcr.io/nanvix/nanvix-sdk-c-clang"
sdk-digest = "sha256:710df6210407984c9dbe4c5cffe643a2ec8033d73853a5c997c7e72ed48af69d"
