[package]
name = "zlib"
version = "1.3.1"
nanvix-version = "0.23.11"

[builds]
[builds.matrix]
platforms = ["microvm"]
modes = ["standalone"]
memory = ["256mb"]

[toolchain]
kind = "nanvix-sdk"
provider = "c-clang"
sdk-version = "v0.23.11-sdk.1"
sdk-image = "ghcr.io/nanvix/nanvix-sdk-c-clang"
sdk-digest = "sha256:33ebefa139d9f116e0b48caebd4935fac27823f0e504d50059a44f5c53f77df8"
