#!/usr/bin/env bash
# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.
#
# Commit the pending image-reference changes, push them to a dedicated
# automation branch, and open (or refresh) a pull request against the
# repository's default branch.
#
# Required environment:
#   TAG                The resolved toolchain tag (e.g. "sha-abcdef0")
#   NEW_IMAGE          Full image reference (e.g. "ghcr.io/nanvix/toolchain-gcc:sha-abcdef0")
#   BRANCH             Name of the automation branch
#   GITHUB_REPOSITORY  "owner/name" (set automatically on Actions)
#   GH_TOKEN           Token usable by `gh` and (when DISPATCH_TOKEN is unset) by `git push`
# Optional environment:
#   DISPATCH_TOKEN     Token used to push so the resulting PR triggers downstream CI
#   ASSIGNEE           GitHub login to assign and request review from

set -euo pipefail

: "${TAG:?TAG is required}"
: "${NEW_IMAGE:?NEW_IMAGE is required}"
: "${BRANCH:?BRANCH is required}"
: "${GITHUB_REPOSITORY:?GITHUB_REPOSITORY is required}"

# At least one of DISPATCH_TOKEN or GH_TOKEN must be set: DISPATCH_TOKEN
# (preferred) is used for pushing so the resulting PR triggers downstream
# CI, and GH_TOKEN is the fallback used by `gh` and `git push`.
if [ -z "${DISPATCH_TOKEN:-}" ] && [ -z "${GH_TOKEN:-}" ]; then
    echo "::error::DISPATCH_TOKEN or GH_TOKEN must be set" >&2
    exit 1
fi

git config user.name "github-actions[bot]"
git config user.email "github-actions[bot]@users.noreply.github.com"

git checkout -B "$BRANCH"
git add -A
git commit -m "[ci] Update Nanvix toolchain image to ${TAG}"

# Prefer DISPATCH_TOKEN so the resulting PR triggers downstream workflows;
# fall back to the ambient GH_TOKEN credentials.
if [ -n "${DISPATCH_TOKEN:-}" ]; then
    git remote set-url origin \
        "https://x-access-token:${DISPATCH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
fi
# Use --force-with-lease so a maintainer hot-fix pushed onto the automation
# branch is not silently clobbered; the lease fails fast if the remote tip
# moved since the last fetch.
git fetch origin "$BRANCH" || true
git push origin "$BRANCH" --force-with-lease

DEFAULT_BRANCH=$(gh repo view --json defaultBranchRef \
    --jq '.defaultBranchRef.name')

PR_TITLE="[ci] Update Nanvix toolchain image to ${TAG}"
PR_BODY=$(cat <<EOF
Automated bump of the Nanvix toolchain Docker image to \`${NEW_IMAGE}\`.

Files updated:
- \`.nanvix/z.py\`
- \`.github/workflows/nanvix-ci.yml\`

Generated by the [Nanvix Update Docker Image](https://github.com/${GITHUB_REPOSITORY}/actions/workflows/nanvix-update-docker-image.yml) workflow.
EOF
)

EXISTING_PR=$(gh pr list \
    --head "$BRANCH" \
    --base "$DEFAULT_BRANCH" \
    --state open \
    --json number \
    --jq '.[0].number // empty' 2>/dev/null || true)

if [ -n "$EXISTING_PR" ]; then
    gh pr edit "$EXISTING_PR" --title "$PR_TITLE" --body "$PR_BODY"
    echo "Updated existing PR #${EXISTING_PR}."
    LATEST_PR="$EXISTING_PR"
else
    PR_URL=$(gh pr create \
        --title "$PR_TITLE" \
        --body "$PR_BODY" \
        --base "$DEFAULT_BRANCH" \
        --head "$BRANCH")
    LATEST_PR="${PR_URL##*/}"
    echo "Opened PR #${LATEST_PR}."
fi

if [ -n "${LATEST_PR:-}" ] && [ -n "${ASSIGNEE:-}" ]; then
    gh pr edit "$LATEST_PR" \
        --add-assignee "$ASSIGNEE" \
        --add-reviewer "$ASSIGNEE" 2>/dev/null || true
fi

if [ -n "${GITHUB_OUTPUT:-}" ]; then
    echo "pr=${LATEST_PR}" >> "$GITHUB_OUTPUT"
fi
